services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    network_mode: "host"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html2
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/error.html:/usr/share/nginx/html/error.html
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  uinx:
    build: .
    container_name: uinx
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - HOST_PROJECT_PATH=${PWD}
    env_file: 
      - ".env"
